reconnect:
  target:
    entity:
      integration: youtube_lounge
      domain: media_player
select_subtitle_track:
  target:
    entity:
      integration: youtube_lounge
      domain: media_player
  fields:
    language_code:
      required: false
      example: 'en'
      default: null
